sudo: required
services:
  - docker

before_install:
  - docker build -t kevinmitaki/docker-intro -f Dockerfile.dev .

script:
  - docker run -e CI=true kevinmitaki/docker-intro npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-intro"
  env: "DockerIntro-env"
  bucket_name: "elasticbeanstalk-eu-west-2-717469761592"
  bucket_path: "docker-intro"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
