version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - usr/app/node_modules
      - ./:/usr/app
